### ISSUE TITLE
Products' images display is broken on French production

### ISSUE THREAD

**Issue by RachL** [openfoodfoundation/ofn-install#289]
## Description
Some example:
https://www.openfoodfrance.org/le-jardin-de-deux-main/shop
https://www.openfoodfrance.org/earl-sandra-et-matthieu-gilbert-pour-pro/shop
https://www.openfoodfrance.org/micromarche-villeenbois/shop

## Expected Behavior
Display products' images when there is one

## Actual Behavior
Images are not displayed

## Steps to Reproduce
Just click on any link provided in description

## Animated Gif/Screenshot

![image](https://user-images.githubusercontent.com/6525576/48918073-8e97a300-ee8a-11e8-8b71-3d9f9e85e409.png)

## Context
Reported by a user

## Severity
bug-s2: a non-critical feature is broken, no workaround

## Your Environment

* Version used: v1.22
* Browser name and version: Firefox 63 and Chrome 70
* Operating System and version (desktop or mobile): Windows and Ubuntu 18 LTS

**Comment by myriamboure** [comment]
There is another issue, the text on the right has moved somehow, isn't it a bit strange ?
![capture du 2018-11-22 21-03-38](https://user-images.githubusercontent.com/8135376/48920616-2cdf3500-ee9a-11e8-9584-5a491c07e28b.png)

**Comment by pacodelaluna** [comment]
I have fixed the issue, last deployment brought back the old S3 configuration, super weird, I will try to get more information about this, I just don't have the old configuration in my files.
But this config is still commented on fr prod secrets.yml, could be a wrong manipulation, I will clean this out, and also remove the old bucket, in order to react faster next time, hey, I mean never ;)

**Comment by RachL** [comment]
Reopening as one shop is still experiencing problems, maybe not the same, but we need to investigate:

https://www.openfoodfrance.org/biosolfruta-ferme-des-7-chemins/shop

**Comment by myriamboure** [comment]
It's not only one shop it's all Suteau Biosol shops where "citrons" and "feuille d'aloe vera" are not displayed @RachL, not sure if all but not only one.

https://www.openfoodfrance.org/biosolfruta-chantonnay-achapti-les-herbiers/shop
https://www.openfoodfrance.org/biosolfruta-haute-goulaine/shop
etc.

but only those two products seem to have an issue... any idea @pacodelaluna  ?

**Comment by myriamboure** [comment]
This is still open, and it seems there are still some issues with some images here and there...
![capture d ecran de 2018-12-14 09-06-38](https://user-images.githubusercontent.com/8135376/50029820-623bf600-fff4-11e8-8688-c99180697653.png)
Is there any way @pacodelaluna to check all images in some automatic way ?
Let's check and if there is no way, let's close... we will open a new issue when it happens again.

**Comment by sauloperez** [comment]
IMO it's not worth spending any time automating this. It will cost a lot of resources both implementing and maintaining it. I'd rather investigate and fix it when it happens.

**Comment by RachL** [comment]
Don't remember how or when. But this can be closed now.
